name: 'TestRail CLI'
description: 'Use the TestRail CLI to interact with TestRail'
inputs:
  host:  # id of input
    description: 'TestRail host URL'
    required: true
  username:
    description: "Authentication username"
    required: true
  password:
    description: "Authentication password"
    required: true
  file_path:
    description: "Path to the JUnit XML file"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.file_path }}
